// Generated by ai/train_meta.py
// Accuracy: 0.94

pub fn predict(mean: f32, var: f32, entropy: f32, zcr: f32) -> u8 {
    if zcr <= 0.4371 {
        1
    } else {
        if zcr <= 0.9131 {
            4
        } else {
            if var <= 5362.8350 {
                if mean <= 129.5265 {
                    3
                } else {
                    4
                }
            } else {
                if var <= 5514.9277 {
                    if zcr <= 0.9202 {
                        1
                    } else {
                        4
                    }
                } else {
                    if entropy <= 7.9509 {
                        1
                    } else {
                        4
                    }
                }
            }
        }
    }
}
