[workspace]
members = [
    "qres_rust/qres_core",
    "qres_rust/qres_daemon",
    "qres_rust/qres_wasm",
    "benchmarks",
    "examples/virtual_iot_network",
    "qres-studio/src-tauri"
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.36", features = ["full"] }
rand = "0.8"
log = "0.4"
zstd = "0.13"
anyhow = "1.0"
thiserror = "1.0"
tract-onnx = "0.21.10"
qres_core = { path = "./qres_rust/qres_core" }
