[workspace]
members = [
    "qres_core",
    "qres_daemon",
    "qres_wasm"
]
resolver = "2"

# Shared dependencies for the workspace
[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.36", features = ["full"] }
rand = "0.8"
log = "0.4"
zstd = "0.13"

# Local dependencies
qres_core = { path = "./qres_core" }
